#!/bin/bash
python /home/software/goagent/local/proxy.py &
# /usr/share/conkycolors/bin/conkyStart &
xrandr --output VGA1 --primary &
xcompmgr -c &
firefox &
emacs &
pidgin &
urxvtd -q -f -o &
c -conkycolors ~/.tconky/conkyrc &
